# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# title: 强哥吉祥
author: 强哥吉祥
# aboutme: 洗洗睡吧 # these are shown on aboutme-sidebar.
aboutme_photo: head.jpg

name: BLOG
email: helloztq@gmail.com
description: 床前明月光，疑是地上霜。举头望明月，低头思故乡。
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
weibo_username: ztq
github_username:  helloztq
# github: helloztq
 # Set this to your UA-# value, or '' to disable the block completely
gaaccount: ''

# The 'comments' setting enables comments. You'll need to select either
# disqus or isso below to choose a comment system. Individual posts can
# override 'comments' to disable on a post-by-post basis.
comments: true

# Set this to your public isso URL to enable comments via isso. Set to '' to disable isso.
isso: ''

# Set this to your disqus shortname to enable comments via disqus. Set to '' to disable disqus.
disqus: ''

permalink: /:title

# Build settings
markdown: kramdown

theme: minima
# theme: jekyll-whiteglass
paginate: 8

gems:
  - jekyll-feed
  - jekyll-paginate
  # - coderay
  
# exclude:
#   - Gemfile
#   - Gemfile.lock




highlighter: rouge
# markdown: kramdown
# gems: ['jekyll-paginate']

# exclude: ['README.md', 'LICENSE'] 
